- platform: uptime

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: ipv4_address
      arg: eth0
    - type: memory_free

- platform: season
