- platform: mqtt
  name: "Media Play/Pause"
  state_topic: ESP32/MediaPlayPause

- platform: mqtt
  name: "Media Next"
  state_topic: ESP32/MediaNext

- platform: mqtt
  name: "Media Previous"
  state_topic: ESP32/MediaPrevious
