# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        - 192.168.1.0/24
        - fd00::/8

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
scene: !include scenes.yaml
python_script: 
mobile_app:
influxdb: !include influxdb.yaml

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
  - platform: microsoft
    api_key: !secret msttskey
    type: Susan, Apollo
    region: uksouth

recorder: !include recorder.yaml

shell_command:
  wledalerter: "/config/shell_command/alert_wled.sh 10 192.168.3.10"

remote:
  - platform: harmony
    name: "Lounge Hub"
    host: 192.168.3.17

media_player:
#  - platform: samsungtv
#    host: 192.168.2.20
#    mac: 5C:49:7D:56:3D:F6
#    port: 8001
#  - platform: samsungtv
#    host: 192.168.2.55
#    name: Soundbar    
  - platform: squeezebox
    host: 192.168.2.21

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_password

weather:
  - platform: darksky
    api_key: !secret darksky_key
    name: Home Weather
    units: uk2

sun:

blink:
  username: !secret blink_username
  password: !secret blink_password

rest_command:
  turn_on_soundbar:
    url: 'http://192.168.2.55:55001/UIC?cmd=%3Cname%3ESetPlaybackControl%3C/name%3E%3Cp%20type=%22str%22%20name=%22playbackcontrol%22%20val=%22play%22/%3E'
  select_aux:
    url: 'http://192.168.2.55:55001/UIC?cmd=%3Cname%3ESetFunc%3C/name%3E%3Cp%20type=%22str%22%20name=%22function%22%20val=%22aux%22/%3E'
  play_chris_country:
    url: 'http://192.168.2.21:9000/status.txt?p0=favorites&p1=playlist&p2=play&p3=item_id:3&p4=shuffle:1&player=00:04:20:23:6c:b4'
  play_first_playlist:
    url: 'http://192.168.2.21:9000/anyurl?p0=playlistcontrol&p1=cmd:load&p2=playlist_id:26127&player=00:04:20:23:6c:b4'
  play_from_dropdown:
    url: 'http://192.168.2.21:9000/anyurl?p0=playlistcontrol&p1=cmd:load&p2=playlist_id:{{ states.input_select.playlists.state|regex_findall_index("\d{3,}", ignorecase=FALSE) }}&player=00:04:20:23:6c:b4'
  play_deezer_flow:
    url: 'http://192.168.2.21:9000/anyurl?p0=playlist&p1=play&p2=deezer%3A%2F%2Fflow.dzr&p3=Deezer%20Flow&player=00%3A04%3A20%3A23%3A6c%3Ab4'


input_select:
  playlists:
    name: LMS playlists
    options:  
      - marc

device_tracker:
  - platform: nmap_tracker
    hosts: 
    - 192.168.1.111
    - 192.168.1.14

hive:
  username: !secret hive_username
  password: !secret hive_password

panel_iframe:
  esphome:
    title: "ESP Home"
    url: http://192.168.2.21:6052/
    icon: mdi:access-point-network
  deconz:
    title: deConz
    icon: mdi:zigbee
    url: http://192.168.2.21:8181
  webmin:
    title: Webmin
    url: http://192.168.2.21:10000/
    icon: mdi:account-badge
  chronograf:
    title: Temperatures
    url: http://192.168.2.21:8888/sources/0/dashboards/2?lower=now%28%29%20-%2012h
    icon: mdi:thermometer


switch:
  - platform: flux
    lights:
      - light.living_room_main
      - light.work_light
    disable_brightness_adjust: true

