- platform: rest
  name: "LMS Playlists"
  resource: http://192.168.1.21:9000/jsonrpc.js
  method: POST
  payload: '{"id":1,"method":"slim.request","params":["",["playlists",0,100]]}'

# Removed this temporarily due to a 256 char limit.  Meh.
#- platform: rest
#  name: "LMS Favourites"
#  resource: http://192.168.1.21:9000/jsonrpc.js
#  method: POST
#  payload: '{"id":1,"method":"slim.request","params":["",["favorites","items",0,100]]}'
